### ISSUE TITLE
Add support for collections & other metadata

### ISSUE THREAD

**Issue by otravers** [suparngp/plex-personal-shows-agent.bundle#1]
Thanks for building this, it's very close to doing everything I need to handle the tutorials I collect. Can you please add support for collections in meta.json, with an array like how you're handling genre tags?

"collections": ["Collection 1", "Collection 2"]

It would also be nice to similarly support the addition of tagline, originally available date, banner or background image, etc.

**Comment by otravers** [comment]
I'm a Python newbie but added these lines to the source code to handle the main additional fields I want:

            metadata.originally_available_at = Datetime.ParseDate(meta_json.get('date', '1900-01-01')).date()
            metadata.collections.clear()
            for collections in meta_json.get('collections', []):
                metadata.collections.add(collections)

**Comment by suparngp** [comment]
Sounds good! I ll add these.

**Comment by suparngp** [comment]
I added these.
